# Generated by Django 2.1.dev20171229175031 on 2018-01-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSVS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='update_at',
        ),
    ]
