# Generated by Django 2.1.dev20171229175031 on 2018-01-23 12:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('SSVS', '0002_remove_schedule_update_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='update_at',
            field=models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='更新日'),
        ),
    ]
