# Generated by Django 2.1.dev20171229175031 on 2018-01-27 01:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SSVS', '0003_schedule_update_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='schedule',
            unique_together={('date', 'time', 'school', 'lesson', 'teacher', 'student')},
        ),
    ]
